# Generated by Django 5.2.15 on 2026-07-01 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Wow Weffles', max_length=80)),
                ('tagline', models.CharField(default='Dulera · Café & Waffle Bar', max_length=160)),
                ('address', models.CharField(default='Main Road, Dulera', max_length=200)),
                ('address_note', models.CharField(blank=True, default='(add exact street address & landmark)', max_length=200)),
                ('phone', models.CharField(default='+91 00000 00000', max_length=40)),
                ('email', models.EmailField(default='hello@wowweffles.cafe', max_length=254)),
                ('hours', models.CharField(default='Mon–Sun · 9:00 AM – 11:00 PM', max_length=120)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
                ('map_embed', models.TextField(blank=True, help_text='Paste the Google Maps <iframe> embed code for your location.')),
            ],
            options={
                'verbose_name': 'Café info',
                'verbose_name_plural': 'Café info',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(help_text="Used for the on-page anchor/URL, e.g. 'tea'.", unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji shown beside the heading, e.g. 🍵', max_length=8)),
                ('tagline', models.CharField(blank=True, help_text="Small note by the heading, e.g. 'Brewed to order'.", max_length=120)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False, help_text="Tick once you've responded.")),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_veg', models.BooleanField(default=False, verbose_name='Vegetarian')),
                ('is_featured', models.BooleanField(default=False, help_text="Show in 'crowd favourites' on the home page.")),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to hide the item (e.g. sold out).')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafe.category')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
